# Generated by Django 4.2.16 on 2025-01-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('max_temperature', models.FloatField()),
                ('alert_count', models.IntegerField()),
                ('acknowledged_by', models.CharField(max_length=100)),
            ],
        ),
    ]
